language: generic
dist: trusty

git:
  depth: 1

script:
  - docker run -it --rm -v `pwd`/elisp/conao3-packages.el:/elisp/init.el conao3/emacs:alpine-min-26.2 emacs --batch -q -l /elisp/init.el --eval="(print (emacs-version))"
  - ip a
