language: generic
dist: trusty

git:
  depth: 1

env:
  global:
    - PO4A_VERSION=0.55

install:
  - perl -E 'say for @INC'
  - echo yes | cpan
  - eval `perl -I$HOME/perl5/lib/perl5 -Mlocal::lib`
  - perl -E 'say for @INC'
  - cpan Module::Build

  - make initialize-po4a

  - export PERL5LIB=`pwd`/po4a-${PO4A_VERSION}/po4a/lib/:$PERL5LIB
  - export PATH=`pwd`/po4a-${PO4A_VERSION}/:$PATH
  - perl -E 'say for @INC'
  - po4a

script:
  - pwd
  - which yes
  - emacs --version
  - perl -v
  - mkdir local
