language: generic
dist: trusty

git:
  depth: 1

env:
  global:
    - PO4A_VERSION=0.55

script:
  - emacs --version
  - perl -v
  - mkdir local
  - perl -E 'say for @INC'
  - perl -Mlocal::lib
  - echo yes | cpan
  - perl -E 'say for @INC'
  - cpan Module::Build
#   - cat cpan-operation.txt | cpan
#   - perl -E 'say for @INC'
#   - cpan Module::Build
#   - curl -LO https://github.com/mquinson/po4a/releases/download/v${PO4A_VERSION}/po4a-${PO4A_VERSION}.tar.gz
#   - tar zxvf po4a-${PO4A_VERSION}.tar.gz
#   - cd po4a-${PO4A_VERSION}
#   - perl Build.PL
#   - ./Build installdeps
