language: generic
dist: trusty

git:
  depth: 1

ENV:
  global:
    - PO4A_VERSION=0.55
script:
  - emacs --version
  - curl -LO https://github.com/mquinson/po4a/releases/download/v${PO4A_VERSION}/po4a-${PO4A_VERSION}.tar.gz
  - tar zxvf po4a-${PO4A_VERSION}.tar.gz
  - cd po4a-${PO4A_VERSION}
  - perl Build.PL
  - ./Build installdeps
