language: generic
sudo: false

git:
  depth: 1

env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
    - EMACS_VERSION=23.4
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=master

install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar xf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs

jobs:
  include:
    - if: branch = master
      stage: "Create melpa recipe archive"
      install: skip
      env:
      script: echo "melpa"

    - if: branch = master
      stage: "melpa archive"
      install: skip
      env:
      script: echo "melpa"

    - if: type = cron
      stage: "cron job"
      install: skip
      env:
      script: echo "cron"
