language: generic
dist: trusty

env:
  global:
    - GIT_COMMITTER_NAME=conao3
    - GIT_COMMITTER_EMAIL=conao3@gmail.com
    - GIT_AUTHOR_NAME=conao3
    - GIT_AUTHOR_EMAIL=conao3@gmail.com

git:
  depth: 1

script:
  - emacs --version
  - emacs -Q --batch -l ./travis-ci/archive-lite.el
  - openssl aes-256-cbc -K $encrypted_c34d5bfe7b07_key -iv $encrypted_c34d5bfe7b07_iv -in travis_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - ./commit

