language: generic
sudo: false

env:
  matrix:
    - EMACS_VERSION=26.1-min
    - EMACS_VERSION=26.2-min
    - EMACS_VERSION=emacs-snapshot

matrix:
  allow_failures:
    - env: EMACS_VERSION=emacs-snapshot

script:
  - make all
