language: generic
dist: trusty

git:
  depth: 1

script:
  - emacs --version
  - emacs -Q --batch -l ./travis-ci/archive-lite.el
  - openssl aes-256-cbc -K $encrypted_c34d5bfe7b07_key -iv $encrypted_c34d5bfe7b07_iv -in travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa
  - git checkout master
  - git add .
  - git commit -m "by Travis CI (job $TRAVIS_JOB_NUMBER)"
  - git push origin master
