language: generic
sudo: false

git:
  depth: 1

env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
        
install:
#  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
#  - tar xf emacs-bin-${EMACS_VERSION}.tar.gz -C /
#  - export EMACS=/tmp/emacs/bin/emacs

jobs:
  include:
    - stage: &mytest
      script: echo "mytest"
    - <<: *mytest
      env: EMACS_VERSION=23.4
      script: echo "mytest"
    - <<: *mytest
      env: EMACS_VERSION=24.5
      script: echo "mytest"
    - <<: *mytest
      env: EMACS_VERSION=25.3
      script: echo "mytest"
    - <<: *mytest
      env: EMACS_VERSION=26.1
      script: echo "mytest"
    - <<: *mytest
      env: EMACS_VERSION=master
      script: echo "mytest"

    - if: branch = master
      stage: "Create melpa recipe archive"
      script: echo "melpa"

    - if: type = cron
      stage: "cron job"
      install: skip
      script: echo "cron"