#!/bin/bash

git remote -v
git remote set-url origin git@github.com:conao3/playground.git

git checkout master
git add .
git commit -m "by Travis CI (job $TRAVIS_JOB_NUMBER) [skip ci]"

git push origin master